[workspace]
members = [
    "crates/core",
    "crates/server",
    "api",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
debug = true
split-debuginfo = "unpacked"

[workspace.dependencies]
derive_more = { version = "1.0", features = ["display", "error", "from"] }
criterion = { version = "0.5", features = ["async_tokio"] }

[workspace.metadata.docs]
targets = ["x86_64-unknown-linux-gnu"]
